<?php

use App\Enums\Gender;
use App\Model\User;
use Ramsey\Uuid\Nonstandard\Uuid;

return [
    new User(
        null,
        'Wouagang',
        'alexrayan@gmail.com',
        password_hash('tkz21', PASSWORD_DEFAULT),
        'Rayan',
        new DateTime('2004-02-03'),
        new DateTime(),
        Gender::MALE,
        'AkidoLD',
        1.74,
    ),
    new User(
        null,
        'Ngono',
        'marie.ngono@example.com',
        password_hash('pass123', PASSWORD_DEFAULT),
        'Marie',
        new DateTime('2001-05-12'),
        new DateTime(),
        Gender::FEMALE,
        'MarieNG',
        1.65,
    ),
    new User(
        null,
        'Tchouameni',
        'paul.tchoua@example.com',
        password_hash('azerty', PASSWORD_DEFAULT),
        'Paul',
        new DateTime('1999-09-21'),
        new DateTime(),
        Gender::MALE,
        'Tchoua99',
        1.80,
    ),
    new User(
        null,
        'Essomba',
        'jess.essomba@example.com',
        password_hash('mypwd', PASSWORD_DEFAULT),
        'Jessica',
        new DateTime('2002-11-10'),
        new DateTime(),
        Gender::FEMALE,
        'JessieE',
        1.70,
    ),
    new User(
        null,
        'Mbarga',
        'richard.mbarga@example.com',
        password_hash('secure01', PASSWORD_DEFAULT),
        'Richard',
        new DateTime('1998-03-17'),
        new DateTime(),
        Gender::MALE,
        'RichMb',
        1.82,
    ),
    new User(
        null,
        'Abena',
        'celine.abena@example.com',
        password_hash('p@ssword', PASSWORD_DEFAULT),
        'Céline',
        new DateTime('2003-07-22'),
        new DateTime(),
        Gender::FEMALE,
        'CelineA',
        1.68,
    ),
    new User(
        null,
        'Nkoum',
        'yvan.nkoum@example.com',
        password_hash('toto123', PASSWORD_DEFAULT),
        'Yvan',
        new DateTime('2000-12-01'),
        new DateTime(),
        Gender::MALE,
        'YvanK',
        1.75,
    ),
    new User(
        null,
        'Kamdem',
        'aline.kamdem@example.com',
        password_hash('alinepw', PASSWORD_DEFAULT),
        'Aline',
        new DateTime('2004-06-14'),
        new DateTime(),
        Gender::FEMALE,
        'LinaK',
        1.60,
    ),
    new User(
        null,
        'Fokou',
        'bernard.fokou@example.com',
        password_hash('bernardpw', PASSWORD_DEFAULT),
        'Bernard',
        new DateTime('1997-08-25'),
        new DateTime(),
        Gender::MALE,
        'FokouB',
        1.78,
    ),
    new User(
        null,
        'Mbah',
        'sandra.mbah@example.com',
        password_hash('sandrapw', PASSWORD_DEFAULT),
        'Sandra',
        new DateTime('2001-01-30'),
        new DateTime(),
        Gender::FEMALE,
        'SanM',
        1.64,
    ),
    new User(
        null,
        'Kouatchou',
        'patrick.kouatchou@example.com',
        password_hash('patrickpw', PASSWORD_DEFAULT),
        'Patrick',
        new DateTime('1995-04-05'),
        new DateTime(),
        Gender::MALE,
        'PatK',
        1.85,
    ),
    new User(
        null,
        'Ndiaye',
        'amina.ndiaye@example.com',
        password_hash('aminapw', PASSWORD_DEFAULT),
        'Amina',
        new DateTime('2002-02-14'),
        new DateTime(),
        Gender::FEMALE,
        'AminaD',
        1.62,
    ),
    new User(
        null,
        'Koumba',
        'serge.koumba@example.com',
        password_hash('sergepw', PASSWORD_DEFAULT),
        'Serge',
        new DateTime('1996-07-19'),
        new DateTime(),
        Gender::MALE,
        'SergK',
        1.77,
    ),
    new User(
        null,
        'Ngongang',
        'stephanie.ngongang@example.com',
        password_hash('stephpw', PASSWORD_DEFAULT),
        'Stéphanie',
        new DateTime('2003-03-11'),
        new DateTime(),
        Gender::FEMALE,
        'StephN',
        1.66,
    ),
    new User(
        null,
        'Djoumessi',
        'frederic.djoumessi@example.com',
        password_hash('fredpw', PASSWORD_DEFAULT),
        'Frédéric',
        new DateTime('2000-10-08'),
        new DateTime(),
        Gender::MALE,
        'FredD',
        1.79,
    ),
    new User(
        null,
        'Ebongue',
        'chloe.ebongue@example.com',
        password_hash('chloepw', PASSWORD_DEFAULT),
        'Chloé',
        new DateTime('2004-12-20'),
        new DateTime(),
        Gender::FEMALE,
        'ChloeE',
        1.63,
    ),
    new User(
        null,
        'Nguema',
        'olivier.nguema@example.com',
        password_hash('olivierpw', PASSWORD_DEFAULT),
        'Olivier',
        new DateTime('1999-09-15'),
        new DateTime(),
        Gender::MALE,
        'OliN',
        1.81,
    ),
    new User(
        null,
        'Mebenga',
        'valerie.mebenga@example.com',
        password_hash('valeriepw', PASSWORD_DEFAULT),
        'Valérie',
        new DateTime('2001-05-09'),
        new DateTime(),
        Gender::FEMALE,
        'ValM',
        1.67,
    ),
    new User(
        null,
        'Onana',
        'kevin.onana@example.com',
        password_hash('kevinpw', PASSWORD_DEFAULT),
        'Kevin',
        new DateTime('1998-11-02'),
        new DateTime(),
        Gender::MALE,
        'KevO',
        1.83,
    ),
    new User(
        null,
        'Talla',
        'noemie.talla@example.com',
        password_hash('noemiepw', PASSWORD_DEFAULT),
        'Noémie',
        new DateTime('2003-09-28'),
        new DateTime(),
        Gender::FEMALE,
        'NoeT',
        1.61,
    ),
];
